package com.everis.equipouno.model;
// Generated 18/09/2019 12:21:43 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name = "alumno", catalog = "escuela")
public class Alumno implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apaterno;
	private String amaterno;
	@JsonIgnore
	private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

	public Alumno() {
	}

	public Alumno(String nombre) {
		this.nombre = nombre;
	}

	public Alumno(String nombre, String apaterno, String amaterno, Set<Inscripcion> inscripcions) {
		this.nombre = nombre;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.inscripcions = inscripcions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apaterno", length = 45)
	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	@Column(name = "amaterno", length = 45)
	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "alumno")
	public Set<Inscripcion> getInscripcions() {
		return this.inscripcions;
	}

	public void setInscripcions(Set<Inscripcion> inscripcions) {
		this.inscripcions = inscripcions;
	}

}
