package com.everis.equipouno.model;
// Generated 18/09/2019 12:21:43 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "escuela")
public class Curso implements java.io.Serializable {

	private int id;
	private String nombrecurso;
	private String descripcion;
	@JsonIgnore
	private Set<Calendario> calendarios = new HashSet<Calendario>(0);

	public Curso() {
	}

	public Curso(int id, String nombrecurso) {
		this.id = id;
		this.nombrecurso = nombrecurso;
	}

	public Curso(int id, String nombrecurso, String descripcion, Set<Calendario> calendarios) {
		this.id = id;
		this.nombrecurso = nombrecurso;
		this.descripcion = descripcion;
		this.calendarios = calendarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombrecurso", nullable = false, length = 45)
	public String getNombrecurso() {
		return this.nombrecurso;
	}

	public void setNombrecurso(String nombrecurso) {
		this.nombrecurso = nombrecurso;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "curso")
	public Set<Calendario> getCalendarios() {
		return this.calendarios;
	}

	public void setCalendarios(Set<Calendario> calendarios) {
		this.calendarios = calendarios;
	}

}
