package com.everis.springbootjprexamen.model;
//Generated 18/09/2019 12:21:43 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
* Alumno generated by hbm2java
*/
@Entity
@Table(name = "product")

public class Product implements java.io.Serializable{

	private Integer id;
	private String nombre;
	private int precio;
		@JsonIgnore
	private Set<Description> descrition = new HashSet<Description>(0);
		private Set<Description> setDescription;
		
		public Product() {
		}

		public Product(String nombre) {
			this.nombre = nombre;
		}

		public Product(String nombre, int precio, Set<Description> descrition) {
			this.nombre = nombre;
			this.precio = precio;
		
		}
		
		@Id
		@GeneratedValue(strategy = IDENTITY)

		@Column(name = "id", unique = true, nullable = false)
		public Integer getId() {
			return this.id;
		}

		public void setId(Integer id) {
			this.id = id;
		}

		@Column(name = "nombre", nullable = false, length = 45)
		public String getNombre() {
			return this.nombre;
		}

		public void setNombre(String nombre) {
			this.nombre = nombre;
		}

		@Column(name = "precio", length = 5000)
		public int getPrecio() {
			return precio;
		}

		public void setPrecio(int precio) {
			this.precio = precio;
		}
		
		@OneToMany(fetch = FetchType.EAGER, mappedBy = "alumno")
		public Set<Description> getDescription() {
			return this.getDescription();
		}

		public void setDescription(Set<Description> description) {
			this.setDescription = description;
		}




}



	
	

